
package com.neusoft.hit.rhin;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "HisService", targetNamespace = "http://www.neusoft.com/hit/rhin", wsdlLocation = "http://192.168.80.97:8080/Ws/HisService.asmx?WSDL")
public class HisService
    extends Service
{

    private final static URL HISSERVICE_WSDL_LOCATION;
    private final static WebServiceException HISSERVICE_EXCEPTION;
    private final static QName HISSERVICE_QNAME = new QName("http://www.neusoft.com/hit/rhin", "HisService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://192.168.80.97:8080/Ws/HisService.asmx?WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        HISSERVICE_WSDL_LOCATION = url;
        HISSERVICE_EXCEPTION = e;
    }

    public HisService() {
        super(__getWsdlLocation(), HISSERVICE_QNAME);
    }

    public HisService(WebServiceFeature... features) {
        super(__getWsdlLocation(), HISSERVICE_QNAME, features);
    }

    public HisService(URL wsdlLocation) {
        super(wsdlLocation, HISSERVICE_QNAME);
    }

    public HisService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, HISSERVICE_QNAME, features);
    }

    public HisService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public HisService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns HisServiceSoap
     */
    @WebEndpoint(name = "HisServiceSoap")
    public HisServiceSoap getHisServiceSoap() {
        return super.getPort(new QName("http://www.neusoft.com/hit/rhin", "HisServiceSoap"), HisServiceSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns HisServiceSoap
     */
    @WebEndpoint(name = "HisServiceSoap")
    public HisServiceSoap getHisServiceSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.neusoft.com/hit/rhin", "HisServiceSoap"), HisServiceSoap.class, features);
    }

    private static URL __getWsdlLocation() {
        if (HISSERVICE_EXCEPTION!= null) {
            throw HISSERVICE_EXCEPTION;
        }
        return HISSERVICE_WSDL_LOCATION;
    }

}
